version: "3.0"

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - 8545:8545
  web:
    build: web
    depends_on:
      - ganache

  ipfs:
    build: ipfs
    ports:
     - 5001:5001

  scproxy:
    build: nginx-proxy
    ports:
      - 80:80
    depends_on:
      - web
      - ipfs
